// <auto-generated />
using System;
using ETicaret.DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ETicaret.DataAccessLayer.Migrations
{
    [DbContext(typeof(ETicaretContext))]
    [Migration("20200404120923_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ETicaret.Entities.TblKategoriler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aktif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GoogleKategorisi")
                        .HasColumnType("int");

                    b.Property<string>("KategoriAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KisaKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaKeywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UstId")
                        .HasColumnType("int");

                    b.Property<int?>("sira")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TblKategoriler");
                });

            modelBuilder.Entity("ETicaret.Entities.TblSepet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TblSepet");
                });

            modelBuilder.Entity("ETicaret.Entities.TblSepetUrunleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Miktar")
                        .HasColumnType("int");

                    b.Property<int?>("SepetId")
                        .HasColumnType("int");

                    b.Property<int?>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SepetId");

                    b.HasIndex("UrunId");

                    b.ToTable("TblSepetUrunleri");
                });

            modelBuilder.Entity("ETicaret.Entities.TblUrunKategori", b =>
                {
                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.HasKey("UrunId", "KategoriId");

                    b.HasIndex("KategoriId");

                    b.ToTable("TblUrunKategori");
                });

            modelBuilder.Entity("ETicaret.Entities.TblUrunler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AlisFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AnaUrunId")
                        .HasColumnType("int");

                    b.Property<bool?>("AyniGunTeslim")
                        .HasColumnType("bit");

                    b.Property<string>("Barkod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BirimId")
                        .HasColumnType("int");

                    b.Property<int?>("Desi")
                        .HasColumnType("int");

                    b.Property<string>("Etiketler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FirsatUrunu")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("GarantiSuresi")
                        .HasColumnType("bit");

                    b.Property<bool?>("Goruntuleme")
                        .HasColumnType("bit");

                    b.Property<bool?>("HizliKargo")
                        .HasColumnType("bit");

                    b.Property<decimal?>("IndirimliFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IndirimliMi")
                        .HasColumnType("bit");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Kdv")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("KdvDahilMi")
                        .HasColumnType("bit");

                    b.Property<string>("KisaAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MarkaId")
                        .HasColumnType("int");

                    b.Property<string>("Meta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("OzelUrun")
                        .HasColumnType("bit");

                    b.Property<string>("ParaBirimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PerakendeFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Resim1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SinirliSayida")
                        .HasColumnType("bit");

                    b.Property<int?>("Stok")
                        .HasColumnType("int");

                    b.Property<decimal?>("ToptanFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("UcretsizKargo")
                        .HasColumnType("bit");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Video")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Vitrin")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TblUrunler");
                });

            modelBuilder.Entity("ETicaret.Entities.TblSepetUrunleri", b =>
                {
                    b.HasOne("ETicaret.Entities.TblSepet", "Sepet")
                        .WithMany("SepetUrunleri")
                        .HasForeignKey("SepetId");

                    b.HasOne("ETicaret.Entities.TblUrunler", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId");
                });

            modelBuilder.Entity("ETicaret.Entities.TblUrunKategori", b =>
                {
                    b.HasOne("ETicaret.Entities.TblKategoriler", "Kategori")
                        .WithMany("UrunKategori")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ETicaret.Entities.TblUrunler", "Urun")
                        .WithMany("UrunKategori")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
